from unittest import TestCase
from unittest.mock import MagicMock, patch
from lodestone_scraper import LodestoneScraper
import json



class TestLodestoneScraper(TestCase):

    def setUp(self):
        self.scraper = LodestoneScraper()

        self.test_char_result = {
            'avg_item_level': 270.0,
             'citystate': "Ul'dah",
             'clan': 'Seeker of the Sun ',
             'current_gear': [("Augmented Shire Custodian's Earrings",
                               'Item Level 270',
                               'Earrings'),
                              ('Alexandrian Neckband of Fending',
                               'Item Level 270',
                               'Necklace'),
                              ('Alexandrian Sollerets of Fending',
                               'Item Level 270',
                               'Feet'),
                              ('Alexandrian Belt of Fending', 'Item Level 270', 'Waist'),
                              ('Soul of the Dark Knight', 'Item Level 30', 'Soul Crystal'),
                              ('Alexandrian Mail of Fending', 'Item Level 270', 'Body'),
                              ('Alexandrian Gauntlets of Fending',
                               'Item Level 270',
                               'Hands'),
                              ("Augmented Shire Custodian's Ring",
                               'Item Level 270',
                               'Ring'),
                              ('Alexandrian Breeches of Fending', 'Item Level 270', 'Legs'),
                              ("Augmented Shire Custodian's Circlet",
                               'Item Level 270',
                               'Head'),
                              ("Augmented Shire Custodian's Bracelet",
                               'Item Level 270',
                               'Bracelets'),
                              ('Augmented Shire Greatsword',
                               'Item Level 270',
                               "Dark Knight's Arm"),
                              ('Alexandrian Ring of Fending', 'Item Level 270', 'Ring')],
             'fc': 'Ascended',
             'gcrank': 'Second Storm Lieutenant',
             'gender': 'Female',
             'grandcompany': 'Maelstrom',
             'guardian': "Nald'thal, the Traders",
             'jobs': [('Paladin', '60', '0 / 4470000'),
                      ('Warrior', '60', '0 / 4470000'),
                      ('Dark Knight', '60', '0 / 4470000'),
                      ('Pugilist', '15', '3586 / 30500'),
                      ('Dragoon', '60', '0 / 4470000'),
                      ('Rogue', '-', '- / -'),
                      ('Samurai', '-', '- / -'),
                      ('White Mage', '60', '0 / 4470000'),
                      ('Scholar', '60', '0 / 4470000'),
                      ('Astrologian', '54', '557158 / 1872000'),
                      ('Bard', '60', '0 / 4470000'),
                      ('Machinist', '-', '- / -'),
                      ('Thaumaturge', '30', '134305 / 162500'),
                      ('Summoner', '60', '0 / 4470000'),
                      ('Red Mage', '-', '- / -'),
                      ('Carpenter', '50', '0 / 864000'),
                      ('Blacksmith', '50', '136538 / 864000'),
                      ('Armorer', '50', '51191 / 864000'),
                      ('Goldsmith', '50', '68060 / 864000'),
                      ('Leatherworker', '50', '11524 / 864000'),
                      ('Weaver', '50', '11829 / 864000'),
                      ('Alchemist', '50', '500 / 864000'),
                      ('Culinarian', '50', '0 / 864000'),
                      ('Miner', '50', '23942 / 864000'),
                      ('Botanist', '59', '16265 / 3888000'),
                      ('Fisher', '-', '- / -')],
             'lodestone_id': '2023059',
             'minions': ['Storm Hatchling',
                         'Black Chocobo Chick',
                         'Princely Hatchling',
                         'Chocobo Chick Courier',
                         'Midgardsormr',
                         'Baby Behemoth',
                         'Morbol Seedling',
                         'Baby Bun',
                         'Chigoe Larva',
                         'Wide-eyed Fawn',
                         'Baby Raptor',
                         'Wolf Pup',
                         'Coeurl Kitten',
                         'Tiny Tortoise',
                         'Dust Bunny',
                         'Pudgy Puk',
                         'Buffalo Calf',
                         'Cactuar Cutting',
                         'Smallshell',
                         'Infant Imp',
                         'Beady Eye',
                         'Fledgling Dodo',
                         'Coblyn Larva',
                         'Goobbue Sproutling',
                         'Bite-sized Pudding',
                         'Demon Brick',
                         'Slime Puddle',
                         'Kidragora',
                         'Onion Prince',
                         'Eggplant Knight',
                         'Garlic Jester',
                         'Tomato King',
                         'Mandragora Queen',
                         'Pumpkin Butler',
                         'Minute Mindflayer',
                         'Tight-beaked Parrot',
                         'Wind-up Brickman',
                         'Baby Opo-opo',
                         'Naughty Nanka',
                         "Mummy's Little Mummy",
                         'Demon Box',
                         'Unicolt',
                         'Owlet',
                         'Ugly Duckling',
                         'Lesser Panda',
                         'Page 63',
                         'Accompaniment Node',
                         'Korpokkur Kid',
                         'Morpho',
                         'Poro Roggo',
                         'Fenrir Pup',
                         'Mammet #003L',
                         'Cait Sith Doll',
                         'Wind-up Moogle',
                         'Wind-up Goblin',
                         'Wind-up Cursor',
                         'Wind-up Airship',
                         'Minion Of Light',
                         'Wind-up Leader',
                         'Wind-up Odin',
                         'Wind-up Gilgamesh',
                         'Wind-up Ultros',
                         'Toy Alexander',
                         'Nana Bear',
                         'Wind-up Warrior Of Light',
                         'Wind-up Firion',
                         'Wind-up Kain',
                         'Wind-up Shantotto',
                         'Magic Broom',
                         'Gold Rush Minecart',
                         'Wind-up Leviathan',
                         'Wind-up Ramuh',
                         'Wind-up Shiva',
                         'Wind-up Minfilia',
                         'Wind-up Thancred',
                         'Dress-up Thancred',
                         'Wind-up Moenbryda',
                         'Wind-up Alphinaud',
                         'Wind-up Cid',
                         'Wind-up Nanamo',
                         'Wind-up Louisoix',
                         'Wind-up Haurchefant',
                         'Wind-up Aymeric',
                         'Wind-up Edda'],
             'mounts': ['Company Chocobo',
                        'Ceremony Chocobo',
                        'Black Chocobo',
                        'Fat Chocobo',
                        'Magitek Armor',
                        'Gilded Magitek Armor',
                        'Coeurl',
                        'War Panther',
                        'Ahriman',
                        'Behemoth',
                        'Warlion',
                        'Griffin',
                        'Zu',
                        'Manacutter',
                        'Gobwalker',
                        "Witch's Broom",
                        'Arrhidaeus',
                        'Unicorn',
                        'Nightmare',
                        'Aithon',
                        'Xanthos',
                        'Gullfaxi',
                        'Markab',
                        'Boreas',
                        'Rose Lanner',
                        'Midgardsormr'],
             'name': 'Oren Iishi',
             'nameday': '25th Sun of the 6th Umbral Moon',
             'race': "Miqo'te"
        }

        self.test_fc_data = {
            'active': 'Always',
             'active_members': '205',
             'estate': {'address': 'Plot 60, 3 Ward, The Goblet (Large)',
                        'greeting': 'The capitol of the entire world.',
                        'name': 'SuperSugoiKarateDojo'},
             'fc_name': 'Ascended',
             'fc_standing': {'Monthly Rank': '6', 'Weekly Rank': '5'},
             'fc_tag': '«AC»',
             'formed': '2015-02-24',
             'gc': 'Maelstrom',
             'gc_standing': '<Allied>',
             'rank': '8',
             'roster': [{'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Roshan Crass',
                         'rank': 'Crownless King'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Abscissa Cartesia',
                         'rank': 'Officer'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Aurifort Popoto',
                         'rank': 'Officer'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Brandon Sharp',
                         'rank': 'Officer'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Cheers Love',
                         'rank': 'Officer'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Kainei Crass',
                         'rank': 'Officer'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Zaia Serafall',
                         'rank': 'Officer'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Ancyra Webb',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Aqua Mirage',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Ashe Nox',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Lazarus Ultima',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Phantom Wings',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'The Highlander',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Tiepo Deis',
                         'rank': 'Raid Leader'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Grid Ur',
                         'rank': 'Guild Crafter'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Kiyuki Raika',
                         'rank': 'Guild Crafter'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Lulu Vivi',
                         'rank': 'Guild Crafter'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Lyreth Nikos',
                         'rank': 'Guild Crafter'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Spicy Legato',
                         'rank': 'Guild Crafter'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Akai Yoru',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Alison Wonderland',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Andoh Bernard',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Aoedus Kanington',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Avicii Hawkmoon',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Cevilia Drieu',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Cooked Ham',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Daelian Cadmus',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': "Darknite Shu'ral",
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Dianora Dawnshadow',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Eanae Hikari',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Fen Zhong',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Geariodin Dymphna',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Haru Ki',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Josh Greene',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Kana Mitsuya',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Kaplan Cadmus',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Katalina Ultima',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Kazuma Yuta',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Klyde Iver',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Kytre Ashaer',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Lani Maduin',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Locke Rockwell',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Lucian Fenrir',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Ozma Black',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Ruki Pykn',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Sato Kayo',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Saya Natsume',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Serifon Raka',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Vella Starr',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '3051637',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/3051637/',
                         'name': 'Yuveria Lior',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Zuzu Zahrah',
                         'rank': 'AC Group Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Bodeman Eternal',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Chross Dash',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Deema Torr',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Dryst Reborn',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Illumi Lumi',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': "L'zentsa Hoshi",
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Lorelei Faeliell',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Lt Law',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Main Ukraine',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Marcus Bloodrain',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Maverick Cannon',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Mikefried Spes',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Noah Nelligan',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Nylea Hunt',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Onyx Kolossus',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Outlaw Starwind',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Pallas Athene',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Razgriz Rodyer',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Saki Yumishi',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Sheepy Turbo',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Shimei Ryomou',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Sirena Owlsong',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Sonata Dusk',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Tatsumi Incursio',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Wacih Bolgi',
                         'rank': 'Raider'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Albireo Lemon',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Anti Anti',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Avyuir Sunstrike',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Blazian Sensei',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Bonbon Iver',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Brak Apollos',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Cassandra Katari',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Celesterra Stoutheart',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Century Killer',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Chloe Lemaire',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Cryptfox Tercero',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Cubix Kyubu',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Cyber Chow',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Dashima Golden',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Elasha Morrigan',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Emilia Tan',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Final Form',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Flere Imsaho',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Floods Oblivion',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Frey Parsnip',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Gray Witch',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Hina Aiko',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Ignis Fatuus',
                         'rank': 'Member'},
                        {'lodestone_id': '7528216',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7528216/',
                         'name': 'Imdesyda Tacdnildun',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Juju Beene',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kai Rosecraft',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kaia Black',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kairune Tolaris',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kato Danzo',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kezia Canadensis',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kizuhan Endo',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Kyrakis Reinhart',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Lelouch Xen',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Little Miiaaaoooo',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Lord Nahodoth',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Lord Tolstedt',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Magic Trick',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Malina Regina',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Maxwell Snart',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Maz Rhya',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Merst Eckson',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Mhala Rhiki',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Michael Stormcloud',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Nghthawk Evenfall',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Niki Heartfire',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Nitnit Kosu',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Noah Ronso',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Onion Sneeze',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Oren Iishi',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Paco Taco',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Pip Tarou',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Pmak Shou',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Sammy Simpson',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Scaredy Cat',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Seda Maharel',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Shinji Chan',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Snoctopus Snoctopus',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Solec Ayr',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Steve Wambold',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Summer Eden',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Sva Tsunami',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Tequila Shots',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Terri Wambold',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Tiercel Nox',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Tiny Rick',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Ulta Sazabic',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Ultima Solidor',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Val Atreides',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Yasashiku Kokoro',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Your Tears',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Yuki Kanase',
                         'rank': 'Member'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Adagio Dazzle',
                         'rank': 'Alt'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Ahri Popoto',
                         'rank': 'Alt'},
                        {'lodestone_id': '7860874',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/7860874/',
                         'name': 'Almond Bomb',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Aqua Nohr',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Aurora Nya',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Azel Nox',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Candy Apple',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Gauri Lala',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Gele Qubele',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Haruko Aki',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Khaleesi Khalasar',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Lala Choko',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Lulu Ruru',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Nalak Izanami',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Rocke Lockwell',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Sakiko Yumishi',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Vexnia Moriko',
                         'rank': 'Alt'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Ari Nagae',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Clorins Azure',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Dobby Deathbringer',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Janna Jun',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Jasnara Calirath',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Korin Ironfur',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Maja Sol',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Manon Batiste',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Meta Giduo',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Mr Corebear',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Mustard Magnus',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': "Oerba Yun'fang",
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Orcah Valthonis',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Orion Falls',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Rorschach Kovac',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Sark Lannis',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Silvana Row',
                         'rank': 'Trial'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Aiko Ta',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Anea Oakhollow',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Anmex Shuggie',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Aurora Nightrose',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': "Busy P'",
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Cecilia Rosa',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Chrome Baby',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': "Death's Scythe",
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Envy Noir',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Franco Ferrucci',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Iknow Uknow',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Insert Cliche',
                         'rank': 'Inactive'},
            {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Khamali Valentine',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Koneko Chan',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Lin Eleyam',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Link Shinagami',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Mus Tache',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Nexius Etherious',
                         'rank': 'Inactive'},
                        {'lodestone_id': '11331772',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/11331772/',
                         'name': 'Predit Blackstar',
                         'rank': 'Inactive'},
                        {'lodestone_id': '17161668',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/17161668/',
                         'name': 'Predit Vain',
                         'rank': 'Inactive'},
                        {'lodestone_id': '17161668',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/17161668/',
                         'name': 'Tamlen Lol',
                         'rank': 'Inactive'},
                        {'lodestone_id': '17161668',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/17161668/',
                         'name': 'Vasa Esmour',
                         'rank': 'Inactive'},
                        {'lodestone_id': '17161668',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/17161668/',
                         'name': 'Zephyr Elysium',
                         'rank': 'Inactive'},
                        {'lodestone_id': '17161668',
                         'lodestone_url': 'http://na.finalfantasyxiv.com/lodestone/character/17161668/',
                         'name': 'Zero Cross',
                         'rank': 'Inactive'}],
             'server': 'Gilgamesh',
             'slogan': 'Please apply at http://ascendedfc.guildwork.com/   We do not '
                       'accept in-game applications.  A true hero never wavers.'
                             }


    def test_search_character(self):
        result = self.scraper.search_character_id('Oren Iishi', 'Gilgamesh')
        self.assertEqual(result, '2023059')


    def test_search_free_company(self):
        result = self.scraper.search_free_company_id('Ascended', 'Gilgamesh')
        self.assertEqual(result, '9232238498621208473')

    @patch('lodestone_scraper.LodestoneScraper.search_character_id', return_value='2023059')
    def test_get_character(self, search_character):

        result = self.scraper.get_character('Oren Iishi', 'Gilgamesh')
        self.assertEqual(result.get('name'), self.test_char_result.get('name'))


    @patch('lodestone_scraper.LodestoneScraper.search_free_company_id', return_value='9232238498621208473')
    def test_get_free_company(self, search_character):

        result = self.scraper.get_free_company('Ascended', 'Gilgamesh')
        self.assertEqual(result.get('fc_name'), self.test_fc_data.get('fc_name'))